<?php 
	/**********************************************************
	 **** File generated by fitzlucassen\DALGenerator tool ****
	 * All right reserved to fitzlucassen repository on github*
	 ************* https://github.com/fitzlucassen ************
	 **********************************************************/
	namespace fitzlucassen\FLFramework\Data\Base\Entity;

	use fitzlucassen\FLFramework\Library\Core;
	use fitzlucassen\FLFramework\Data\Entity;

	class CocktailcocktailmenumealBase  {
		private $_id;
		private $_id_Menu;
		private $_id_Meal;
		private $_creationDate;
		private $_queryBuilder;

		public function __construct($id = '', $id_Menu = '', $id_Meal = '', $creationDate = ''){
			$this->_queryBuilder = new Core\QueryBuilder(true);
			$this->fillObject(array("id" => $id, "id_Menu" => $id_Menu, "id_Meal" => $id_Meal, "creationDate" => $creationDate));
		}

		/***********
		 * GETTERS *
		 ***********/
		public function getId() {
			return $this->_id;
		}
		public function getId_Menu() {
			return $this->_id_Menu;
		}
		public function getId_Meal() {
			return $this->_id_Meal;
		}
		public function getCreationDate() {
			return $this->_creationDate;
		}
		/*******
		 * END *
		 *******/

		public function fillObject($properties) {
			if(!empty($properties["id"]))
				$this->_id = $properties["id"];
			if(!empty($properties["id_Menu"]))
				$this->_id_Menu = $properties["id_Menu"];
			if(!empty($properties["id_Meal"]))
				$this->_id_Meal = $properties["id_Meal"];
			if(!empty($properties["creationDate"]))
				$this->_creationDate = $properties["creationDate"];
		}
	}
