<?php 
	/**********************************************************
	 **** File generated by fitzlucassen\DALGenerator tool ****
	 * All right reserved to fitzlucassen repository on github*
	 ************* https://github.com/fitzlucassen ************
	 **********************************************************/
	namespace fitzlucassen\FLFramework\Data\Base\Entity;

	use fitzlucassen\FLFramework\Library\Core;
	use fitzlucassen\FLFramework\Data\Entity;

	class HeaderBase  {
		private $_id;
		private $_title;
		private $_metaDescription;
		private $_metaKeywords;
		private $_lang;
		private $_queryBuilder;

		public function __construct($id = '', $title = '', $metaDescription = '', $metaKeywords = '', $lang = ''){
			$this->_queryBuilder = new Core\QueryBuilder(true);
			$this->fillObject(array("id" => $id, "title" => $title, "metaDescription" => $metaDescription, "metaKeywords" => $metaKeywords, "lang" => $lang));
		}

		/***********
		 * GETTERS *
		 ***********/
		public function getId() {
			return $this->_id;
		}
		public function getTitle() {
			return $this->_title;
		}
		public function getMetaDescription() {
			return $this->_metaDescription;
		}
		public function getMetaKeywords() {
			return $this->_metaKeywords;
		}
		public function getLang() {
			return $this->_lang;
		}
		/*******
		 * END *
		 *******/

		public function fillObject($properties) {
			if(!empty($properties["id"]))
				$this->_id = $properties["id"];
			if(!empty($properties["title"]))
				$this->_title = $properties["title"];
			if(!empty($properties["metaDescription"]))
				$this->_metaDescription = $properties["metaDescription"];
			if(!empty($properties["metaKeywords"]))
				$this->_metaKeywords = $properties["metaKeywords"];
			if(!empty($properties["lang"]))
				$this->_lang = $properties["lang"];
		}
	}
