<?php 
	/**********************************************************
	 **** File generated by fitzlucassen\DALGenerator tool ****
	 * All right reserved to fitzlucassen repository on github*
	 ************* https://github.com/fitzlucassen ************
	 **********************************************************/
	namespace fitzlucassen\FLFramework\Data\Base\Entity;

	use fitzlucassen\FLFramework\Library\Core;
	use fitzlucassen\FLFramework\Data\Entity;

	class LesterrassesmealBase  {
		private $_id;
		private $_id_Category;
		private $_description;
		private $_price;
		private $_creationDate;
		private $_queryBuilder;

		public function __construct($id = '', $id_Category = '', $description = '', $price = '', $creationDate = ''){
			$this->_queryBuilder = new Core\QueryBuilder(true);
			$this->fillObject(array("id" => $id, "id_Category" => $id_Category, "description" => $description, "price" => $price, "creationDate" => $creationDate));
		}

		/***********
		 * GETTERS *
		 ***********/
		public function getId() {
			return $this->_id;
		}
		public function getId_Category() {
			return $this->_id_Category;
		}
		public function getDescription() {
			return $this->_description;
		}
		public function getPrice() {
			return $this->_price;
		}
		public function getCreationDate() {
			return $this->_creationDate;
		}
		/*******
		 * END *
		 *******/

		public function fillObject($properties) {
			if(!empty($properties["id"]))
				$this->_id = $properties["id"];
			if(!empty($properties["id_Category"]))
				$this->_id_Category = $properties["id_Category"];
			if(!empty($properties["description"]))
				$this->_description = $properties["description"];
			if(!empty($properties["price"]))
				$this->_price = $properties["price"];
			if(!empty($properties["creationDate"]))
				$this->_creationDate = $properties["creationDate"];
		}
	}
