<?php 
	/**********************************************************
	 **** File generated by fitzlucassen\DALGenerator tool ****
	 * All right reserved to fitzlucassen repository on github*
	 ************* https://github.com/fitzlucassen ************
	 **********************************************************/
	namespace fitzlucassen\FLFramework\Data\Base\Entity;

	use fitzlucassen\FLFramework\Library\Core;
	use fitzlucassen\FLFramework\Data\Entity;

	class RequestBase  {
		private $_id;
		private $_id_User;
		private $_isCompany;
		private $_companyName;
		private $_companySiret;
		private $_firstname;
		private $_lastname;
		private $_phoneNumber;
		private $_email;
		private $_fromCompany;
		private $_message;
		private $_zone;
		private $_eventZipcode;
		private $_eventDate;
		private $_eventTime;
		private $_people;
		private $_isCommand;
		private $_creationDate;
		private $_queryBuilder;

		public function __construct($id = '', $id_User = '', $isCompany = '', $companyName = '', $companySiret = '', $firstname = '', $lastname = '', $phoneNumber = '', $email = '', $fromCompany = '', $message = '', $zone = '', $eventZipcode = '', $eventDate = '', $eventTime = '', $people = '', $isCommand = '', $creationDate = ''){
			$this->_queryBuilder = new Core\QueryBuilder(true);
			$this->fillObject(array("id" => $id, "id_User" => $id_User, "isCompany" => $isCompany, "companyName" => $companyName, "companySiret" => $companySiret, "firstname" => $firstname, "lastname" => $lastname, "phoneNumber" => $phoneNumber, "email" => $email, "fromCompany" => $fromCompany, "message" => $message, "zone" => $zone, "eventZipcode" => $eventZipcode, "eventDate" => $eventDate, "eventTime" => $eventTime, "people" => $people, "isCommand" => $isCommand, "creationDate" => $creationDate));
		}

		/***********
		 * GETTERS *
		 ***********/
		public function getId() {
			return $this->_id;
		}
		public function getId_User() {
			return $this->_id_User;
		}
		public function getIsCompany() {
			return $this->_isCompany;
		}
		public function getCompanyName() {
			return $this->_companyName;
		}
		public function getCompanySiret() {
			return $this->_companySiret;
		}
		public function getFirstname() {
			return $this->_firstname;
		}
		public function getLastname() {
			return $this->_lastname;
		}
		public function getPhoneNumber() {
			return $this->_phoneNumber;
		}
		public function getEmail() {
			return $this->_email;
		}
		public function getFromCompany() {
			return $this->_fromCompany;
		}
		public function getMessage() {
			return $this->_message;
		}
		public function getZone() {
			return $this->_zone;
		}
		public function getEventZipcode() {
			return $this->_eventZipcode;
		}
		public function getEventDate() {
			return $this->_eventDate;
		}
		public function getEventTime() {
			return $this->_eventTime;
		}
		public function getPeople() {
			return $this->_people;
		}
		public function getIsCommand() {
			return $this->_isCommand;
		}
		public function getCreationDate() {
			return $this->_creationDate;
		}
		/*******
		 * END *
		 *******/

		public function fillObject($properties) {
			if(!empty($properties["id"]))
				$this->_id = $properties["id"];
			if(!empty($properties["id_User"]))
				$this->_id_User = $properties["id_User"];
			if(!empty($properties["isCompany"]))
				$this->_isCompany = $properties["isCompany"];
			if(!empty($properties["companyName"]))
				$this->_companyName = $properties["companyName"];
			if(!empty($properties["companySiret"]))
				$this->_companySiret = $properties["companySiret"];
			if(!empty($properties["firstname"]))
				$this->_firstname = $properties["firstname"];
			if(!empty($properties["lastname"]))
				$this->_lastname = $properties["lastname"];
			if(!empty($properties["phoneNumber"]))
				$this->_phoneNumber = $properties["phoneNumber"];
			if(!empty($properties["email"]))
				$this->_email = $properties["email"];
			if(!empty($properties["fromCompany"]))
				$this->_fromCompany = $properties["fromCompany"];
			if(!empty($properties["message"]))
				$this->_message = $properties["message"];
			if(!empty($properties["zone"]))
				$this->_zone = $properties["zone"];
			if(!empty($properties["eventZipcode"]))
				$this->_eventZipcode = $properties["eventZipcode"];
			if(!empty($properties["eventDate"]))
				$this->_eventDate = $properties["eventDate"];
			if(!empty($properties["eventTime"]))
				$this->_eventTime = $properties["eventTime"];
			if(!empty($properties["people"]))
				$this->_people = $properties["people"];
			if(!empty($properties["isCommand"]))
				$this->_isCommand = $properties["isCommand"];
			if(!empty($properties["creationDate"]))
				$this->_creationDate = $properties["creationDate"];
		}
	}
