<?php 
	/**********************************************************
	 **** File generated by fitzlucassen\DALGenerator tool ****
	 * All right reserved to fitzlucassen repository on github*
	 ************* https://github.com/fitzlucassen ************
	 **********************************************************/
	namespace fitzlucassen\FLFramework\Data\Base\Entity;

	use fitzlucassen\FLFramework\Library\Core;
	use fitzlucassen\FLFramework\Data\Entity;

	class RequestcartBase  {
		private $_id;
		private $_id_Request;
		private $_id_Menu;
		private $_id_Meal;
		private $_quantity;
		private $_queryBuilder;

		public function __construct($id = '', $id_Request = '', $id_Menu = '', $id_Meal = '', $quantity = ''){
			$this->_queryBuilder = new Core\QueryBuilder(true);
			$this->fillObject(array("id" => $id, "id_Request" => $id_Request, "id_Menu" => $id_Menu, "id_Meal" => $id_Meal, "quantity" => $quantity));
		}

		/***********
		 * GETTERS *
		 ***********/
		public function getId() {
			return $this->_id;
		}
		public function getId_Request() {
			return $this->_id_Request;
		}
		public function getId_Menu() {
			return $this->_id_Menu;
		}
		public function getId_Meal() {
			return $this->_id_Meal;
		}
		public function getQuantity() {
			return $this->_quantity;
		}
		/*******
		 * END *
		 *******/

		public function fillObject($properties) {
			if(!empty($properties["id"]))
				$this->_id = $properties["id"];
			if(!empty($properties["id_Request"]))
				$this->_id_Request = $properties["id_Request"];
			if(!empty($properties["id_Menu"]))
				$this->_id_Menu = $properties["id_Menu"];
			if(!empty($properties["id_Meal"]))
				$this->_id_Meal = $properties["id_Meal"];
			if(!empty($properties["quantity"]))
				$this->_quantity = $properties["quantity"];
		}
	}
