<?php 
	/**********************************************************
	 **** File generated by fitzlucassen\DALGenerator tool ****
	 * All right reserved to fitzlucassen repository on github*
	 ************* https://github.com/fitzlucassen ************
	 **********************************************************/
	namespace fitzlucassen\FLFramework\Data\Base\Entity;

	use fitzlucassen\FLFramework\Library\Core;
	use fitzlucassen\FLFramework\Data\Entity;

	class ZipcodezoneBase  {
		private $_id;
		private $_zipcode;
		private $_zone;
		private $_queryBuilder;

		public function __construct($id = '', $zipcode = '', $zone = ''){
			$this->_queryBuilder = new Core\QueryBuilder(true);
			$this->fillObject(array("id" => $id, "zipcode" => $zipcode, "zone" => $zone));
		}

		/***********
		 * GETTERS *
		 ***********/
		public function getId() {
			return $this->_id;
		}
		public function getZipcode() {
			return $this->_zipcode;
		}
		public function getZone() {
			return $this->_zone;
		}
		/*******
		 * END *
		 *******/

		public function fillObject($properties) {
			if(!empty($properties["id"]))
				$this->_id = $properties["id"];
			if(!empty($properties["zipcode"]))
				$this->_zipcode = $properties["zipcode"];
			if(!empty($properties["zone"]))
				$this->_zone = $properties["zone"];
		}
	}
