<?php 
	/**********************************************************
	 **** File generated by fitzlucassen\DALGenerator tool ****
	 * All right reserved to fitzlucassen repository on github*
	 ************* https://github.com/fitzlucassen ************
	 **********************************************************/
	namespace fitzlucassen\FLFramework\Data\Repository;

	use fitzlucassen\FLFramework\Library\Core;
	use fitzlucassen\FLFramework\Data\Entity;
	use fitzlucassen\FLFramework\Data\Base\Entity as EntityBase;
	use fitzlucassen\FLFramework\Data\Base\Repository as RepositoryBase;

	class NewsRepository extends RepositoryBase\NewsRepositoryBase {
		public function __construct($pdo, $lang) {
			parent::__construct($pdo, $lang);
		}

		public function getLastThreeNews() {
			$query = $this->_queryBuilder
				->select()
				->from(array("news"))
				->where(array(array("link" => "", "left" => "fromCompany", "operator" => "=", "right" => "Les Terrasses de Courbevoie")))
				->orderBy(['id DESC'])
				->limit(3)
				->getQuery();

			try {
				$properties = $this->_pdoHelper->selectTable($query);
				$array = array();
				foreach ($properties as $object){
					$o = new Entity\News();
					$o->fillObject($object);
					$array[] = $o;
				}
				return $array;
			}
			catch(\PDOException $e){
				print $e->getMessage();
			}
			return array();
		}
	}
