<?php 
	/**********************************************************
	 **** File generated by fitzlucassen\DALGenerator tool ****
	 * All right reserved to fitzlucassen repository on github*
	 ************* https://github.com/fitzlucassen ************
	 **********************************************************/
	namespace fitzlucassen\FLFramework\Data\Repository;

	use fitzlucassen\FLFramework\Library\Core;
	use fitzlucassen\FLFramework\Data\Entity;
	use fitzlucassen\FLFramework\Data\Base\Entity as EntityBase;
	use fitzlucassen\FLFramework\Data\Base\Repository as RepositoryBase;

	class RouteurlRepository extends RepositoryBase\RouteurlRepositoryBase {
		public function __construct($pdo, $lang) {
			parent::__construct($pdo, $lang);
		}

		public function getByControllerAction($controller, $action) {
			$request = $this->_queryBuilder->select()
							->from(array("routeurl"))
							->where(array(array("link" => "", "left" => "controller", "operator" => "=", "right" => $controller),
									array("link" => "AND", "left" => "action", "operator" => "=", "right" => $action)))
							->getQuery();
			try {
				$resultat = $this->_pdoHelper->Select($request);

				$RouteUrl = new Entity\Routeurl($resultat["id"], $resultat["name"], $resultat["controller"], $resultat["action"], $resultat["order"]);

				return $RouteUrl;
			} catch (\PDOException $e) {
				print $e->getMessage();
			}
			return array();
		}
	}
