<?php 
	/**********************************************************
	 **** File generated by fitzlucassen\DALGenerator tool ****
	 * All right reserved to fitzlucassen repository on github*
	 ************* https://github.com/fitzlucassen ************
	 **********************************************************/
	namespace fitzlucassen\FLFramework\Data\Entity;

	use fitzlucassen\FLFramework\Library\Core;
	use fitzlucassen\FLFramework\Data\Base\Entity as EntityBase;

	class Request extends EntityBase\RequestBase {
		public function __construct($id = '', $id_User = '', $isCompany = '', $companyName = '', $companySiret = '', $firstname = '', $lastname = '', $phoneNumber = '', $email = '', $fromCompany = '', $message = '', $eventDate = '', $eventTime = '', $people = '', $creationDate = ''){
			parent::__construct($id, $id_User, $isCompany, $companyName, $companySiret, $firstname, $lastname, $phoneNumber, $email, $fromCompany, $message, $eventDate, $eventTime, $people, $creationDate);
		}

	}
