<?php 
	/**********************************************************
	 **** File generated by fitzlucassen\DALGenerator tool ****
	 * All right reserved to fitzlucassen repository on github*
	 ************* https://github.com/fitzlucassen ************
	 **********************************************************/
	namespace fitzlucassen\FLFramework\Data\Entity;

	use fitzlucassen\FLFramework\Library\Core;
	use fitzlucassen\FLFramework\Data\Base\Entity as EntityBase;

	class Rewrittingurl extends EntityBase\RewrittingurlBase {
		public function __construct($id = '', $idRouteUrl = '', $urlMatched = '', $lang = ''){
			parent::__construct($id, $idRouteUrl, $urlMatched, $lang);
		}

	}
