<?php 
	/**********************************************************
	 **** File generated by fitzlucassen\DALGenerator tool ****
	 * All right reserved to fitzlucassen repository on github*
	 ************* https://github.com/fitzlucassen ************
	 **********************************************************/
	namespace fitzlucassen\FLFramework\Data\Entity;

	use fitzlucassen\FLFramework\Library\Core;
	use fitzlucassen\FLFramework\Data\Base\Entity as EntityBase;

	class Routeurl extends EntityBase\RouteurlBase {
		public function __construct($id = '', $name = '', $controller = '', $action = '', $order = ''){
			parent::__construct($id, $name, $controller, $action, $order);
		}

	}
