<?php 
	/**********************************************************
	 **** File generated by fitzlucassen\DALGenerator tool ****
	 * All right reserved to fitzlucassen repository on github*
	 ************* https://github.com/fitzlucassen ************
	 **********************************************************/
	namespace fitzlucassen\FLFramework\Data\Entity;

	use fitzlucassen\FLFramework\Library\Core;
	use fitzlucassen\FLFramework\Data\Base\Entity as EntityBase;

	class User extends EntityBase\UserBase {
		public function __construct($id = '', $isCompany = '', $companyName = '', $companySiret = '', $firstname = '', $lastname = '', $phoneNumber = '', $email = '', $isActive = '', $fromCompany = '', $creationDate = ''){
			parent::__construct($id, $isCompany, $companyName, $companySiret, $firstname, $lastname, $phoneNumber, $email, $isActive, $fromCompany, $creationDate);
		}

	}
